#!/bin/bash
#date >> ${OPENSHIFT_PYTHON_LOG_DIR}/testCronMin.log
#echo "hello from the daily test cron job" >> ${OPENSHIFT_PYTHON_LOG_DIR}/testCronMin.log

DUMP_FILE_NAME="~/app-root/data/backups/mysqlPython"
DUMP_DATE=`date +%Y-%m-%d`
DUMP_EXT="dmp"
echo "dumping: "${DUMP_FILE_NAME}"-"${DUMP_DATE}"."${DUMP_EXT}

#dump the mysql python schema
mysqldump --skip-lock-tables -h $OPENSHIFT_MYSQL_DB_HOST -P ${OPENSHIFT_MYSQL_DB_PORT:-3306} -u ${OPENSHIFT_MYSQL_DB_USERNAME:-'admin'}  --password="$OPENSHIFT_MYSQL_DB_PASSWORD" python > ${DUMP_FILE_NAME}"-"${DUMP_DATE}"."${DUMP_EXT}

#zip the dumps 
find ~/app-root/data/backup -regex 'mysqlPython-[0-9][0-9][0-9][0-9]\-[0-9][0-9]\-[0-9][0-9].dmp' -type f -exec gzip "{}" ";"

#delete old dumps
find ~/app-root/data/backup -mtime 30 -type f -exec rm -f "{}" ";"

