#!/bin/bash
#date >> ${OPENSHIFT_PYTHON_LOG_DIR}/testCronMin.log
#echo "hello from the daily test cron job" >> ${OPENSHIFT_PYTHON_LOG_DIR}/testCronMin.log

mysqldump --skip-lock-tables -h $OPENSHIFT_MYSQL_DB_HOST -P ${OPENSHIFT_MYSQL_DB_PORT:-3306} -u ${OPENSHIFT_MYSQL_DB_USERNAME:-'admin'}  --password="$OPENSHIFT_MYSQL_DB_PASSWORD" python > ~/app-root/data/backups/testDump

